color0 #101923
color1 #ffb4ab
color2 #4ecc6e
color3 #ccc24e
color4 #ffb962
color5 #dfc1a2
color6 #86a9d5
color7 #ebe1d9
color8 #1e324a
color9 #ffcbc4
color10 #75f295
color11 #f2e875
color12 #ffc47b
color13 #ffe9d3
color14 #b7d5fb
color15 #ffffff
background #101923
selection_foreground #472a00
cursor #ffb962
cursor_text_color #472a00
foreground #ebe1d9
selection_background #ffb962
active_border_color #ffb962
inactive_border_color #dfc1a2

active_tab_foreground   #472a00
active_tab_background   #ffb962
inactive_tab_foreground #c7d0db
inactive_tab_background #1e324a
cursor_trail_color      #c7d0db
